# --- SUPER-LEVEL OS HARDWARE BRIDGE (v0.3) ---

# 1. CORE GPU PIPELINE (ZINK + TURNIP KGSL)
export GALLIUM_DRIVER=zink
export MESA_LOADER_DRIVER_OVERRIDE=zink
export TU_DEBUG=noconform,kgsl
export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/freedreno_icd.aarch64.json

# 2. RUNTIME & IPC
export DISPLAY=:0
export XDG_RUNTIME_DIR=/run/user/1000
export PULSE_SERVER=tcp:127.0.0.1:4713

# 3. PERFORMANCE OVERRIDES
export vblank_mode=0
export MESA_GL_VERSION_OVERRIDE=4.6
export MESA_GLSL_VERSION_OVERRIDE=460
export ZINK_DESCRIPTORS=lazy
export MESA_GLTHREAD=true
export MESA_VK_WSI_PRESENT_MODE=mailbox 

# 4. BROWSER & DECODER BRIDGE
export MOZ_DISABLE_RDD_SANDBOX=1
export MOZ_ENABLE_WAYLAND=0
export MOZ_X11_EGL=1
export MOZ_ACCELERATED_VIDEO=1
export MOZ_WEBRENDER=1

# VA-API Hardware Decoding via Zink
export LIBVA_DRIVER_NAME=zink
export VDPAU_DRIVER=zink

# 5. IPC LATENCY FIX
export PULSE_LATENCY_MSEC=50
